global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'benchmark-rest'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']
    scrape_interval: 5s

  - job_name: 'spring-app-2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081']
    scrape_interval: 5s

  - job_name: 'spring-app-3'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8082']
    scrape_interval: 5s

